### ISSUE TITLE
Move dev guide to single page to make navigation easier

### ISSUE THREAD

**Issue by PietrH** [b-cubed-eu/documentation#34]
Currently I find it unclear on how to get from page to page on the dev guide website. 

For example, when navigating from the introduction page https://docs.b-cubed.eu/dev-guide/ to the page on repositories https://docs.b-cubed.eu/dev-guide/code-repositories/, or R: https://docs.b-cubed.eu/dev-guide/r/ it's not immidiatly clear to me that I'd have to navigate via the header menu

![image](https://github.com/b-cubed-eu/documentation/assets/48065851/7187567e-e16f-4f26-ace9-4421f74afcd2)

I believe it might be better put everything on a single page instead. Then we can:

- Use the navigation on the side get to major headers
- Use Ctrl + F for search

Example:

![image](https://github.com/b-cubed-eu/documentation/assets/48065851/42a322d1-a616-4d37-bd4c-eb9eef24ddb8)

Already briefly discussed with Peter. What do you think?

**Comment by peterdesmet** [comment]
Note to self:

- [ ] Bundle
- [ ] Chapter authors
- [ ] Headings
- [ ] References
- [ ] Internal links
