### ISSUE TITLE
Add vignettes from gcube

### ISSUE THREAD

**Issue by peterdesmet** [b-cubed-eu/documentation#45]
@wlangera can you ping me when the gcube vignettes are ready to be linked to from https://docs.b-cubed.eu/ ?

**Comment by wlangera** [comment]
Yes, it is on my to do list. First I will go on holidays, afterwards I will publish the biohackrxiv preprint, and then v1.0.0 of gcube.
And then it will be ready (I will ping you).

Cheers

**Comment by wlangera** [comment]
Hi Peter

Version 1.0.0 is released. I will publish it later this week to Zenodo.
Can you add these vignettes to the documentation website?

**gcube**, a software package to simulate biodiversity data cubes using the R programming language.

- **Get started**: https://b-cubed-eu.github.io/gcube/#example
- **1. Simulating the occurrence process**: https://b-cubed-eu.github.io/gcube/articles/occurrence-process.html
- **2. Simulating the detection process**: https://b-cubed-eu.github.io/gcube/articles/detection-process.html
- **3. Specifying the grid designation process**: https://b-cubed-eu.github.io/gcube/articles/grid-designation-process.html
- **4. Creating cubes for multiple species**: https://b-cubed-eu.github.io/gcube/articles/multi_species_approach.html
